services:
    main:
        container_name: jury-main
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - VITE_JURY_NAME=${JURY_NAME}
            - PORT=8000
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                - VITE_JURY_NAME=${JURY_NAME}
                - VITE_JURY_URL=/api
                - VITE_HUB=${HEHE:-}
        ports:
            - ${PORT:-8000}:8000
